function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // INFO
	global.__objectDepths[1] = 0; // obj_player
	global.__objectDepths[2] = 0; // obj_pokeball
	global.__objectDepths[3] = 1; // obj_seller
	global.__objectDepths[4] = 1; // obj_seller_super
	global.__objectDepths[5] = 1; // obj_vacuum
	global.__objectDepths[6] = 0; // obj_egg_parent
	global.__objectDepths[7] = 0; // obj_pokemon_parent
	global.__objectDepths[8] = 0; // obj_rock_parent
	global.__objectDepths[9] = 0; // obj_grass_parent
	global.__objectDepths[10] = 0; // obj_fire_parent
	global.__objectDepths[11] = 0; // obj_water_parent
	global.__objectDepths[12] = 0; // obj_flying_parent
	global.__objectDepths[13] = 0; // obj_electic_parent
	global.__objectDepths[14] = 0; // obj_ground_parent
	global.__objectDepths[15] = 0; // obj_item_parent
	global.__objectDepths[16] = 0; // obj_stone_parent
	global.__objectDepths[17] = 0; // obj_solid_parent
	global.__objectDepths[18] = 0; // obj_terrain_parent
	global.__objectDepths[19] = 0; // obj_shop_btn_parent
	global.__objectDepths[20] = 0; // obj_abra
	global.__objectDepths[21] = 0; // obj_bellsprout
	global.__objectDepths[22] = 0; // obj_bulbasaur
	global.__objectDepths[23] = 0; // obj_caterpie
	global.__objectDepths[24] = 0; // obj_charmander
	global.__objectDepths[25] = 0; // obj_diglett
	global.__objectDepths[26] = 0; // obj_eevee
	global.__objectDepths[27] = 0; // obj_ekans
	global.__objectDepths[28] = 0; // obj_geodude
	global.__objectDepths[29] = 0; // obj_growlith
	global.__objectDepths[30] = 0; // obj_igglybuff
	global.__objectDepths[31] = 0; // obj_machop
	global.__objectDepths[32] = 0; // obj_mankey
	global.__objectDepths[33] = 0; // obj_meowth
	global.__objectDepths[34] = 0; // obj_nidoran
	global.__objectDepths[35] = 0; // obj_oddish
	global.__objectDepths[36] = 0; // obj_onix
	global.__objectDepths[37] = 0; // obj_paris
	global.__objectDepths[38] = 0; // obj_pichu
	global.__objectDepths[39] = 0; // obj_pidgey
	global.__objectDepths[40] = 0; // obj_poliwag
	global.__objectDepths[41] = 0; // obj_ponyta
	global.__objectDepths[42] = 0; // obj_poochyena
	global.__objectDepths[43] = 0; // obj_psyduck
	global.__objectDepths[44] = 0; // obj_rattata
	global.__objectDepths[45] = 0; // obj_sandshrew
	global.__objectDepths[46] = 0; // obj_shellder
	global.__objectDepths[47] = 0; // obj_spearow
	global.__objectDepths[48] = 0; // obj_squirtle
	global.__objectDepths[49] = 0; // obj_tentacool
	global.__objectDepths[50] = 0; // obj_torkoal
	global.__objectDepths[51] = 0; // obj_treeko
	global.__objectDepths[52] = 0; // obj_venonat
	global.__objectDepths[53] = 0; // obj_vulpix
	global.__objectDepths[54] = 0; // obj_weedle
	global.__objectDepths[55] = 0; // obj_zubat
	global.__objectDepths[56] = 1; // obj_shop_menu
	global.__objectDepths[57] = 0; // obj_stones_btn
	global.__objectDepths[58] = 0; // obj_badges_btn
	global.__objectDepths[59] = 0; // obj_pokemon_f_btn
	global.__objectDepths[60] = 0; // obj_pokemon_m_btn
	global.__objectDepths[61] = 0; // obj_pokemon_non_btn
	global.__objectDepths[62] = 0; // obj_terrain_btn
	global.__objectDepths[63] = 0; // obj_items_btn
	global.__objectDepths[64] = 0; // obj_terrain_mode_btn
	global.__objectDepths[65] = 0; // obj_up_btn
	global.__objectDepths[66] = 0; // obj_exit_btn
	global.__objectDepths[67] = 0; // obj_pokemon_buy_btn_parent
	global.__objectDepths[68] = 0; // obj_terrain_buy_btn_parent
	global.__objectDepths[69] = 0; // obj_item_buy_btn_parent
	global.__objectDepths[70] = 0; // obj_stone_buy_btn_parent
	global.__objectDepths[71] = 0; // obj_rock_1
	global.__objectDepths[72] = 0; // obj_rock_2
	global.__objectDepths[73] = 0; // obj_coin
	global.__objectDepths[74] = 0; // obj_ember_1
	global.__objectDepths[75] = 0; // obj_ember_2
	global.__objectDepths[76] = 0; // obj_bubble_1
	global.__objectDepths[77] = 0; // obj_bubble_2
	global.__objectDepths[78] = 0; // obj_steam
	global.__objectDepths[79] = 0; // obj_whirlwind_1
	global.__objectDepths[80] = 0; // obj_flower_1
	global.__objectDepths[81] = 0; // obj_flower_2
	global.__objectDepths[82] = 0; // obj_mushroom_1
	global.__objectDepths[83] = 0; // obj_diglett_trail
	global.__objectDepths[84] = 0; // obj_spark_1
	global.__objectDepths[85] = 1; // obj_breedpad
	global.__objectDepths[86] = 0; // obj_fence4_h
	global.__objectDepths[87] = 0; // obj_fence4_v
	global.__objectDepths[88] = 0; // obj_fence8_h
	global.__objectDepths[89] = 0; // obj_fence8_v
	global.__objectDepths[90] = 0; // obj_gate8_h
	global.__objectDepths[91] = 0; // obj_gate8_v
	global.__objectDepths[92] = 0; // obj_perm_fence4_h
	global.__objectDepths[93] = 0; // obj_perm_fence4_v
	global.__objectDepths[94] = 1; // obj_truck_brock


	global.__objectNames[0] = "INFO";
	global.__objectNames[1] = "obj_player";
	global.__objectNames[2] = "obj_pokeball";
	global.__objectNames[3] = "obj_seller";
	global.__objectNames[4] = "obj_seller_super";
	global.__objectNames[5] = "obj_vacuum";
	global.__objectNames[6] = "obj_egg_parent";
	global.__objectNames[7] = "obj_pokemon_parent";
	global.__objectNames[8] = "obj_rock_parent";
	global.__objectNames[9] = "obj_grass_parent";
	global.__objectNames[10] = "obj_fire_parent";
	global.__objectNames[11] = "obj_water_parent";
	global.__objectNames[12] = "obj_flying_parent";
	global.__objectNames[13] = "obj_electic_parent";
	global.__objectNames[14] = "obj_ground_parent";
	global.__objectNames[15] = "obj_item_parent";
	global.__objectNames[16] = "obj_stone_parent";
	global.__objectNames[17] = "obj_solid_parent";
	global.__objectNames[18] = "obj_terrain_parent";
	global.__objectNames[19] = "obj_shop_btn_parent";
	global.__objectNames[20] = "obj_abra";
	global.__objectNames[21] = "obj_bellsprout";
	global.__objectNames[22] = "obj_bulbasaur";
	global.__objectNames[23] = "obj_caterpie";
	global.__objectNames[24] = "obj_charmander";
	global.__objectNames[25] = "obj_diglett";
	global.__objectNames[26] = "obj_eevee";
	global.__objectNames[27] = "obj_ekans";
	global.__objectNames[28] = "obj_geodude";
	global.__objectNames[29] = "obj_growlith";
	global.__objectNames[30] = "obj_igglybuff";
	global.__objectNames[31] = "obj_machop";
	global.__objectNames[32] = "obj_mankey";
	global.__objectNames[33] = "obj_meowth";
	global.__objectNames[34] = "obj_nidoran";
	global.__objectNames[35] = "obj_oddish";
	global.__objectNames[36] = "obj_onix";
	global.__objectNames[37] = "obj_paris";
	global.__objectNames[38] = "obj_pichu";
	global.__objectNames[39] = "obj_pidgey";
	global.__objectNames[40] = "obj_poliwag";
	global.__objectNames[41] = "obj_ponyta";
	global.__objectNames[42] = "obj_poochyena";
	global.__objectNames[43] = "obj_psyduck";
	global.__objectNames[44] = "obj_rattata";
	global.__objectNames[45] = "obj_sandshrew";
	global.__objectNames[46] = "obj_shellder";
	global.__objectNames[47] = "obj_spearow";
	global.__objectNames[48] = "obj_squirtle";
	global.__objectNames[49] = "obj_tentacool";
	global.__objectNames[50] = "obj_torkoal";
	global.__objectNames[51] = "obj_treeko";
	global.__objectNames[52] = "obj_venonat";
	global.__objectNames[53] = "obj_vulpix";
	global.__objectNames[54] = "obj_weedle";
	global.__objectNames[55] = "obj_zubat";
	global.__objectNames[56] = "obj_shop_menu";
	global.__objectNames[57] = "obj_stones_btn";
	global.__objectNames[58] = "obj_badges_btn";
	global.__objectNames[59] = "obj_pokemon_f_btn";
	global.__objectNames[60] = "obj_pokemon_m_btn";
	global.__objectNames[61] = "obj_pokemon_non_btn";
	global.__objectNames[62] = "obj_terrain_btn";
	global.__objectNames[63] = "obj_items_btn";
	global.__objectNames[64] = "obj_terrain_mode_btn";
	global.__objectNames[65] = "obj_up_btn";
	global.__objectNames[66] = "obj_exit_btn";
	global.__objectNames[67] = "obj_pokemon_buy_btn_parent";
	global.__objectNames[68] = "obj_terrain_buy_btn_parent";
	global.__objectNames[69] = "obj_item_buy_btn_parent";
	global.__objectNames[70] = "obj_stone_buy_btn_parent";
	global.__objectNames[71] = "obj_rock_1";
	global.__objectNames[72] = "obj_rock_2";
	global.__objectNames[73] = "obj_coin";
	global.__objectNames[74] = "obj_ember_1";
	global.__objectNames[75] = "obj_ember_2";
	global.__objectNames[76] = "obj_bubble_1";
	global.__objectNames[77] = "obj_bubble_2";
	global.__objectNames[78] = "obj_steam";
	global.__objectNames[79] = "obj_whirlwind_1";
	global.__objectNames[80] = "obj_flower_1";
	global.__objectNames[81] = "obj_flower_2";
	global.__objectNames[82] = "obj_mushroom_1";
	global.__objectNames[83] = "obj_diglett_trail";
	global.__objectNames[84] = "obj_spark_1";
	global.__objectNames[85] = "obj_breedpad";
	global.__objectNames[86] = "obj_fence4_h";
	global.__objectNames[87] = "obj_fence4_v";
	global.__objectNames[88] = "obj_fence8_h";
	global.__objectNames[89] = "obj_fence8_v";
	global.__objectNames[90] = "obj_gate8_h";
	global.__objectNames[91] = "obj_gate8_v";
	global.__objectNames[92] = "obj_perm_fence4_h";
	global.__objectNames[93] = "obj_perm_fence4_v";
	global.__objectNames[94] = "obj_truck_brock";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
